### ISSUE TITLE
Issue compiling from clean build

### ISSUE THREAD

**Issue by dlew** [evant/gradle-retrolambda#105]
I've started running into an issue with retrolambda and the latest AppCompat release.

Steps to reproduce:

1. Update AppCompat dependency on a project to 22.1.1
1. Run `./gradlew clean`
1. Run `./gradlew compile` (Yes, separately from the last step - done together it worked sometimes)
1. See this error if you are using lambdas inside of a class extending `FragmentActivity`:

```
Error! Failed to transform some classes
java.lang.RuntimeException: java.lang.IllegalAccessException: no such method: com.trello.common.TFragmentActivity.lambda$bindObservable$214(Observable)Observable/invokeSpecial
	at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:42)
	at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.backportLambda(BackportLambdaInvocations.java:105)
	at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.visitInvokeDynamicInsn(BackportLambdaInvocations.java:94)
	at net.orfjackal.retrolambda.asm.ClassReader.readCode(ClassReader.java:1439)
	at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:1017)
	at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
	at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
	at net.orfjackal.retrolambda.Transformers.lambda$transform$4(Transformers.java:106)
	at net.orfjackal.retrolambda.Transformers$$Lambda$2/2007328737.accept(Unknown Source)
	at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:120)
	at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:106)
	at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:46)
	at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:72)
	at net.orfjackal.retrolambda.Main.main(Main.java:26)
Caused by: java.lang.IllegalAccessException: no such method: com.trello.common.TFragmentActivity.lambda$bindObservable$214(Observable)Observable/invokeSpecial
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:872)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:993)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1379)
	at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:997)
	at net.orfjackal.retrolambda.lambdas.Types.toMethodHandle(Types.java:42)
	at net.orfjackal.retrolambda.lambdas.Types.asmToJdkType(Types.java:19)
	at net.orfjackal.retrolambda.lambdas.LambdaReifier.callBootstrapMethod(LambdaReifier.java:106)
	at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:37)
	... 13 more
Caused by: java.lang.NoClassDefFoundError: android/support/v4/view/LayoutInflaterFactory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:25)
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:965)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
	... 19 more
Caused by: java.lang.ClassNotFoundException: android.support.v4.view.LayoutInflaterFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:27)
	... 32 more
```

The strangest part is that doing a non-clean build will work, though I suspect that's because it's skipping the retrolambda step.

This happens with retrolambda 2.0.0 or 2.0.2 (I tried both).

These are not static method calls.

**Comment by evant** [comment]
Looks like adding
```groovy
retrolambda {
    jvmArgs '-noverify'
}
```
fixes it, probably related to #31. Makes me wonder what the hell google is using to compile their code. @orfjackal is there anything you can do in retrolambda itself to fix this, or do we need to complain to google?

**Comment by wheelerruss** [comment]
@evant the above worked for me, thanks

**Comment by orfjackal** [comment]
Hmm, I'll need to look into it to check whether the reason is the same as in #31. ClassNotFoundException hints at something else.

One workaround would be for Retrolambda to add some preprosessing to Android libraries in order to fix the stack map frames and such things, so that Oracle Java can load the classes.

**Comment by jondwillis** [comment]
@orfjackal `-noverify` also works for me. It started showing up only on my build server after I upgraded support libraries from 22.0.0 to 22.1.1.

**Comment by kjpublic01** [comment]
Same thing happening for me after "upgrading" to support-v4 22.1.1. -noverify works for me also.

**Comment by lolkittens** [comment]
I'm having the same issue under the same conditions, -noverify works here as well.

It seems odd to me that the support-v4-22.1.1-sources.jar contains the LayoutInflaterFactory source file, but the classes.jar from support-v4-22.1.1.aar doesn't contain a compiled version.

**Comment by magicgoose** [comment]
> Same thing happening for me after "upgrading" to support-v4 22.1.1. -noverify works for me also.

And same thing with me.

**Comment by rdtorres** [comment]
+1 with the same issue and "-noverify" works for me, but I'm not comfortable with it.

**Comment by rdtorres** [comment]
I could figure out what is wrong. Basically a jar is missing. 

During the execution of ':app:compileRetrolambdaDebug' it includes, among many other jars, "exploded-aar/com.android.support/appcompat-v7/22.1.1/jars/classes.jar", but the "exploded-aar/com.android.support/support-v4/22.1.1/jars/libs/internal_impl-22.1.1.jar" is missing. 

Now I will try to find a way to fix it.

**Comment by evant** [comment]
Oh that's interesting, is it somehow not making it onto the retrolambda classpath?

**Comment by rdtorres** [comment]
Yes. This jars/libs/internal_impl-22.1.1.jar is not part of the retrolambda classpath. This is the reason why it is failing. We need to understand now why it is not there.

**Comment by rafaelekol** [comment]
Where exactly should I add this part of code? I already tried to add in Gradle, but with no effect.

```
retrolambda {
        jvmArgs '-noverify'
    }
```
My error looks like this
```
Didn't find class "com.example.com.app.CreateProfileActivity$$Lambda$2" on path: DexPathList[[zip file...
```

**Comment by magicgoose** [comment]
@rafaelekol 

	tasks.whenTaskAdded { task ->
	    if (task.name.startsWith("lint")) {
	        task.enabled = false
	    }
	}

	apply plugin: 'com.android.application'
	apply plugin: 'me.tatarka.retrolambda'

	retrolambda {
	    jvmArgs '-noverify'
	}

	android {
		// the rest of the script

**Comment by orfjackal** [comment]
@rafaelekol Your error looks more like https://github.com/orfjackal/retrolambda/issues/37 in which case -noverify is not a solution. Does it work if you do a clean build?

**Comment by WonderCsabo** [comment]
I just encountered this problem. It is weird, because it only happens *sometimes*. I can verify what @rdtorres is saying, the **internal_impl.jar** is not on the retrolambda classpath *sometimes*. I do not know what is happening, because i am always running a clean build. :confused:

**Comment by WonderCsabo** [comment]
Sorry, i can consistently reproduce the problem, if i ran the tasks in different commands, like the OP says:

`$ gradlew clean`
`$ gradlew assembleDebug`

When i am running the two tasks in the same command, it is just *sometimes* failing:

`$ gradlew clean assembleDebug`

So the problem is: the **internal_impl.jar** is not added to the Retrolambda classpath.

**Comment by rspeyer** [comment]
+1 we are having this problem on a semi-regular basis as well. Is there any known workaround? None of the above workarounds have worked for us

**Comment by xorgate** [comment]
It does seem that the -noverify indeed supresses the error, but it also reduces my confidence in my build.
I reckon we will be able to remove this line when Google updates the support library?

**Comment by WonderCsabo** [comment]
@xorgate as it is explained by @rdtorres and me, it is not a problem how the support lib is compiled, the real problem is that the support lib is not on the retrolambda classpath *at all*. AFAIK.

**Comment by NachoSoto** [comment]
We started hitting this issue recently as well. Somehow it's getting more frequent now.
Cleaning and rebuilding temporarily fixes the problem.

I don't think this has anything to do with the support library (at least in our case), as we're reproducing this problem in a pure-java library.

**Comment by ypresto** [comment]
Wrote workaround here: https://github.com/orfjackal/retrolambda/issues/37#issuecomment-114092779

**Comment by WonderCsabo** [comment]
@ypresto are you sure it works? If you run `clean` before `assemble`, all the output from `prepare${build_variant}Dependencies` will be deleted, rendering that task totally unnecessary. Am i missing sg?

**Comment by ypresto** [comment]
I tried twice on Circle CI and MBP, then both succeeded.
Perhaps because classpath is determined before clean task is launched, I think.

**Comment by WonderCsabo** [comment]
Well, this fails for me. This is what you meant?
```sh
./gradlew prepareDebugDependencies
./gradlew clean
./gradlew assembleDebug

**Comment by ypresto** [comment]
oh, sorry...

`./gradlew clean assembleDebug` would be pass.

**Comment by ypresto** [comment]
But I think it is not recommended to clean after prepare (because dependencies might be updated in 2nd execution).

**Comment by WonderCsabo** [comment]
I think you are just lucky. As we wrote that on this issue, if you add `clean` in the same command, it sometimes passes. I think your workaround cannot work, because `clean` deletes everything.

This whole issue is about cleaning. :wink: If you do not clean, this issue is not present at all.

**Comment by ypresto** [comment]
> sometimes failing

Ahh, I see.
Note that I configured Circle CI for workaround something like below:

```
./gradlew clean prepareDebugDependencies
./gradlew testDebug
```

**Comment by WonderCsabo** [comment]
@ypresto i can confirm your last workaround is good. Thanks!

This issue is really change, though. Maybe it is a bug in the Gradle Android plugin.

**Comment by evant** [comment]
Was able to fix this by delaying when the classpath is caluclated for retrolambda. Note, the probably does _not_ fix https://github.com/evant/gradle-retrolambda/issues/60 as it is probably a seperate issue.

**Comment by ypresto** [comment]
Confirmed fix in our CI env. Thanks! :tada:

**Comment by 3mph4515** [comment]
I have faced with the same issue:
```
     Caused by: java.lang.ClassNotFoundException: Didn't find class "foo.StartExamStopFragment$$Lambda$2" on path: DexPathList[[zip file "/data/app/foo-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
```

Using retrolambda:3.2.0. The problem occurs in random time at line view 
```
ViewObservable.clicks().subs
```

-noverify paramets doesn't help. Can fix this issue only with clear cache and invalidating.

**Comment by ypresto** [comment]
@3mph4515

Maybe it is #60, can you try `incremental false`?
https://github.com/evant/gradle-retrolambda/issues/60#issuecomment-119241477

**Comment by denis-itskovich** [comment]
Might be this issue is related to this one: #134 
If it is related, this version should fix it:

    buildscript {
            repositories {
                maven { url "https://jitpack.io" }
            }
            dependencies {
                classpath 'com.github.denis-itskovich:gradle-retrolambda:3.2.3-fix-134'
            }
    }
