### ISSUE TITLE
Build fails when running connected android tests

### ISSUE THREAD

**Issue by eliasbagley** [evant/gradle-retrolambda#173]
I'm using: `classpath 'me.tatarka:gradle-retrolambda:3.3.0-beta4'` with Android Studio 2.0 and Gradle 2.11

I get the following error when I run: `./gradlew connectedAndroidTest`

```
Parallel execution is an incubating feature.
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:preStagingBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2320Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72320Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2320Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72320Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42320Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2320Library UP-TO-DATE
:app:prepareComCrashlyticsSdkAndroidAnswers120Library UP-TO-DATE
:app:prepareComCrashlyticsSdkAndroidBeta112Library UP-TO-DATE
:app:prepareComCrashlyticsSdkAndroidCrashlytics224Library UP-TO-DATE
:app:prepareComF2prateekRxPreferencesRxPreferences100Library UP-TO-DATE
:app:prepareComGithubBrianPlummerTinydancer009Library UP-TO-DATE
:app:prepareComGithubGcacaceSignaturePad103Library UP-TO-DATE
:app:prepareComH6ah4iAndroidWidgetAdvrecyclerviewAdvrecyclerview086Library UP-TO-DATE
:app:prepareComHannesdorfmannSqlbriteDao041Library UP-TO-DATE
:app:prepareComJakewhartonHugoHugoRuntime110Library UP-TO-DATE
:app:prepareComJakewhartonProcessPhoenix102Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbinding020Library UP-TO-DATE
:app:prepareComJakewhartonThreetenabpThreetenabp102Library UP-TO-DATE
:app:prepareComJakewhartonTimberTimber401Library UP-TO-DATE
:app:prepareComJoanzapataIconifyAndroidIconify211Library UP-TO-DATE
:app:prepareComJoanzapataIconifyAndroidIconifyFontawesome211Library UP-TO-DATE
:app:prepareComMattpreciousTelescopeTelescope150Library UP-TO-DATE
:app:prepareComRocketmadeMetricsglobalPaymentGatewayLibrary UP-TO-DATE
:app:prepareComSquareupLeakcanaryLeakcanaryAndroid131Library UP-TO-DATE
:app:prepareComSquareupSqlbriteSqlbrite041Library UP-TO-DATE
:app:prepareIoFabricSdkAndroidFabric131Library UP-TO-DATE
:app:prepareIoReactivexRxandroid110Library UP-TO-DATE
:app:prepareUkCoChrisjenxCalligraphy210Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:fabricGenerateResourcesDebug
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugResources
:app:generateDebugSources
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:prePackageMarkerForDebug
:app:transformClassesWithRetrolambdaForDebug UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportTestEspressoEspressoContrib221Library UP-TO-DATE
:app:prepareComAndroidSupportTestEspressoEspressoCore221Library UP-TO-DATE
:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource221Library UP-TO-DATE
:app:prepareComAndroidSupportTestExposedInstrumentationApiPublish041Library UP-TO-DATE
:app:prepareComAndroidSupportTestRules041Library UP-TO-DATE
:app:prepareComAndroidSupportTestRunner041Library UP-TO-DATE
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl UP-TO-DATE
:app:processDebugAndroidTestManifest UP-TO-DATE
:app:compileDebugAndroidTestRenderscript UP-TO-DATE
:app:generateDebugAndroidTestBuildConfig UP-TO-DATE
:app:generateDebugAndroidTestAssets UP-TO-DATE
:app:mergeDebugAndroidTestAssets UP-TO-DATE
:app:generateDebugAndroidTestResValues UP-TO-DATE
:app:generateDebugAndroidTestResources UP-TO-DATE
:app:mergeDebugAndroidTestResources UP-TO-DATE
:app:processDebugAndroidTestResources UP-TO-DATE
:app:generateDebugAndroidTestSources UP-TO-DATE
:app:compileDebugAndroidTestJavaWithJavac
:app:compileDebugAndroidTestNdk UP-TO-DATE
:app:compileDebugAndroidTestSources
:app:prePackageMarkerForDebugAndroidTest
:app:transformClassesWithRetrolambdaForDebugAndroidTest FAILED

BUILD FAILED

Total time: 3.094 secs

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithRetrolambdaForDebugAndroidTest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
	at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
	at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:163)
	at org.gradle.api.internal.project.AbstractProject.javaexec(AbstractProject.java:817)
	at org.gradle.api.internal.project.AbstractProject.javaexec(AbstractProject.java:813)
	at me.tatarka.RetrolambdaExec.exec(RetrolambdaExec.groovy:37)
	at me.tatarka.RetrolambdaTransform$_transform_closure1$_closure4.doCall(RetrolambdaTransform.groovy:72)
	at me.tatarka.RetrolambdaTransform$_transform_closure1.doCall(RetrolambdaTransform.groovy:47)
	at me.tatarka.RetrolambdaTransform.transform(RetrolambdaTransform.groovy:42)
	at com.android.build.api.transform.Transform.transform(Transform.java:308)
	at com.android.build.gradle.internal.pipeline.TransformTask$3.call(TransformTask.java:178)
	at com.android.build.gradle.internal.pipeline.TransformTask$3.call(TransformTask.java:174)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
```

Everything works when I use `classpath 'me.tatarka:gradle-retrolambda:3.2.5`t

**Comment by letientai299** [comment]
+1. 
The same issue here. I also want to confirm that `3.2.5` work fine.

**Comment by lsuski** [comment]
I confirm, 3.3.0-beta4 doesn't work with android tests

**Comment by DreierF** [comment]
+1
Same issue for me with `3.3.0-beta4`

**Comment by kidinov** [comment]
Same here
