### ISSUE TITLE
Error:A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by lengyue524** [evant/gradle-retrolambda#218]
rertolambda is 3.3.1
Error when I sync the project.IDE log is:
```
Caused by: java.lang.NullPointerException
	at me.tatarka.RetrolambdaPluginAndroid.configureCompileJavaTask(RetrolambdaPluginAndroid.groovy:74)
	at me.tatarka.RetrolambdaPluginAndroid.access$3(RetrolambdaPluginAndroid.groovy)
	at me.tatarka.RetrolambdaPluginAndroid$_apply_closure5.doCall(RetrolambdaPluginAndroid.groovy:64)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
	at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:92)
	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:692)
	at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
	at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 54 more
```
how to fix it?

**Comment by PDDStudio** [comment]
@lengyue524 How did you manage to get rid of this Exception?

**Comment by pollux-** [comment]
For me, ` jackOptions {
            enabled true
        }` was enabled, removing this helped me

**Comment by chnouman** [comment]
removing jackoptions help me.

**Comment by ranjitkathiriya** [comment]
useJack true


        jackOptions {
            enabled true
        } 

remove this work fro me..

**Comment by Endi327** [comment]
For me, dataBinding { enabled true } was enabled in gradle, removing this helped me

**Comment by raashidewan** [comment]
@pollux- @ranjitkathiriya Where did you find that line in gradle?
