### ISSUE TITLE
class file for java.lang.invoke.MethodType not found

### ISSUE THREAD

**Issue by dziobas** [evant/gradle-retrolambda#23]
I tried to setup new sample project and it can't compile.

```
An exception has occurred in the compiler (1.8.0_05). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
```

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJava'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35) 
.
.
.
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
    at org.gradle.api.internal.tasks.compile.jdk6.Jdk6JavaCompiler.execute(Jdk6JavaCompiler.java:47)
    at org.gradle.api.internal.tasks.compile.jdk6.Jdk6JavaCompiler.execute(Jdk6JavaCompiler.java:38)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:96)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:49)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:35)
    at org.gradle.api.internal.tasks.compile.DelegatingJavaCompiler.execute(DelegatingJavaCompiler.java:29)
    at org.gradle.api.internal.tasks.compile.DelegatingJavaCompiler.execute(DelegatingJavaCompiler.java:20)
    at org.gradle.api.internal.tasks.compile.IncrementalJavaCompilerSupport.execute(IncrementalJavaCompilerSupport.java:33)
    at org.gradle.api.internal.tasks.compile.IncrementalJavaCompilerSupport.execute(IncrementalJavaCompilerSupport.java:24)
    at org.gradle.api.tasks.compile.Compile.compile(Compile.java:67)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:533)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:516)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 72 more
```

Setup is similar as in the doc except:

```
retrolambda {
    jdk System.getenv("JAVA8_HOME")
    oldJdk System.getenv("JAVA7_HOME")
    javaVersion JavaVersion.VERSION_1_7
}
```

Environment variables are set to:
/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home
respectively.

**Comment by hanibalsk** [comment]
I got the same error when I used in RxJava lambda alternative of this:

```java
new Func1<Throwable, Boolean>() {
   @Override
   public Boolean call(Throwable throwable) {
            return false;
   }
}
```
it was in RxJava method onErrorReturn. It was in unit test.

Solution for me was using old way interface

**Comment by mgrzechocinski** [comment]
Hey,

I think we need to reopen this issue. Gradle plugin - v1.1.0-rc1 introduced basic support for unit tests. When you use lambda expressions in a unit test (as @hanibalsk mentioned in above comment) compiler fails with

```
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
```

I had no time to investigate it deeper, but I guess there's now separated task for compiling test sources, like `compileUnittTestJava`, and since Retrolambda gradle plugin substitutes `compile<Variant>Java` task it might be needed to do the same for `compile<Variant>UnitTestJava`. At first sight seems like it doesn't do that, so compiler fails on compiling unit tests' sources.

We'd appreciate to have it fixed, since unit testing now becomes a little less pain as before and more people starts writing them :)

**Comment by evant** [comment]
Thanks, I created a new issue for it https://github.com/evant/gradle-retrolambda/issues/86

**Comment by ericfri** [comment]
I too am having a very similar issue.  Except it has started once I upgraded to Android Studio 2 preview.  I get the error 
> An exception has occurred in the compiler (1.8.0_65). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
Error:Execution failed for task ':Autosense:compilePaidDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

If I compile from the command line everything works.  
I've got posts on the [Android Studio bug list](https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&groupby=&sort=&id=197416) as well as [Stackoverflow](http://stackoverflow.com/questions/34236051/gradle-task-compilepaiddebugjavawithjavac-fails-in-android-studio?noredirect=1#comment56219087_34236051)

**Comment by chakrit** [comment]
@hanibalsk what is the "old way interface" you mention? I'm using a lot of the `Callable` thing and now my code breaks with the exact same error : (

**Comment by vipheyue** [comment]
i delete this 
  retrolambda {
  jdk System.getenv("JAVA8_HOME")
  oldJdk System.getenv("JAVA6_HOME")
  javaVersion JavaVersion.VERSION_1_6
  jvmArgs '-arg1', '-arg2'
  defaultMethods false
  incremental true
}   


then  OK!!
