### ISSUE TITLE
Gradle warning for use of deprecated method getClassesDir

### ISSUE THREAD

**Issue by ubschmidt2** [evant/gradle-retrolambda#264]
Gradle (4+) outputs the following warning:
```
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
	at org.gradle.api.internal.tasks.DefaultSourceSetOutput.getClassesDir(DefaultSourceSetOutput.java:79)
	at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getClassesDir(Unknown Source)
	at me.tatarka.RetrolambdaPluginJava$_apply_closure1$_closure2.doCall(RetrolambdaPluginJava.groovy:43)

...
```

**Comment by evant** [comment]
Released version 3.7.1 which should be compatible with gradle 5+
