### ISSUE TITLE
Failing with Glass

### ISSUE THREAD

**Issue by coderoshi** [evant/gradle-retrolambda#53]
I'm ran into these problems with retrolambda 2.4.0 and 2.3.0.

Google Glass requires: compileSdkVersion "Google Inc.:Glass Development Kit Preview:19"
I first had to create a simlink from android-19 to "Google Inc.:Glass Development Kit Preview:19". Now retrolambda found android.jar. 

The next problem was `app:_compileDebugJava`.

```
17:43:35.270 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -d /Users/ericredmond/AndroidStudioProjects/ContextSurgery/app/build/retrolambda/debug -g -bootclasspath /Users/ericredmond/AndroidStudioProjects/ContextSurgery/app/build/retrolambda/Google Inc.:Glass Development Kit Preview:19/android.jar ...
17:43:35.272 [INFO] [org.gradle.api.internal.tasks.compile.jdk6.Jdk6JavaCompiler] Compiling with JDK Java compiler API.
17:43:35.802 [ERROR] [system.err] Fatal Error: Unable to find package java.lang in classpath or bootclasspath
17:43:35.804 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:_compileDebugJava'
17:43:35.804 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:_compileDebugJava FAILED
```

Fine. I set `exclude 'Debug'`. That got a bit further, but then started getting the bad class file magic problem.

```
:app:dexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
...
```

That was the furthest I could get.

**Comment by evant** [comment]
version 3.0.0 no longer does android jar patching shenanigans, it should work fine with whatever android sdk you are using.
